DROP TABLE IF EXISTS TBL_HEROES;
 
CREATE TABLE TBL_HEROES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  superhero_name VARCHAR(250) DEFAULT NULL
);

DROP TABLE IF EXISTS TBL_MISSIONS;
 
CREATE TABLE TBL_MISSIONS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  mission_name VARCHAR(250) NOT NULL,
  is_deleted BOOLEAN NOT NULL,
  is_completed BOOLEAN NOT NULL
);

DROP TABLE IF EXISTS HEROES_MISSIONS;
CREATE TABLE HEROES_MISSIONS (
  heroes_id INT,
  missions_id INT
);


